export const commQuestions = [
  {
    id: 1,
    question: "What is the role of communication in development work?",
    keywords: ["awareness", "engagement", "behavioral change"],
    scoreMode: "keyword",
  },
  {
    id: 2,
    question: "How can storytelling be used in social impact communication?",
    keywords: ["real-life stories", "emotional connect", "case studies"],
    scoreMode: "keyword",
  },
  {
    id: 3,
    question: "What makes a message effective for rural audiences?",
    keywords: ["simple language", "visuals", "local dialect"],
    scoreMode: "keyword",
  },
  {
    id: 4,
    question: "How would you communicate a health initiative to tribal communities?",
    keywords: ["pictorial content", "vernacular", "on-ground demos"],
    scoreMode: "keyword",
  },
  {
    id: 5,
    question: "What is IEC and how is it different from BCC?",
    keywords: ["Information", "Education", "Communication", "behavior change"],
    scoreMode: "keyword",
  },
  {
    id: 6,
    question: "How do you ensure inclusivity in communication campaigns?",
    keywords: ["diverse voices", "gender-sensitive", "accessible formats"],
    scoreMode: "keyword",
  },
  {
    id: 7,
    question: "How does social media help an NGO or Foundation like TSF?",
    keywords: ["visibility", "engagement", "awareness"],
    scoreMode: "keyword",
  },
  {
    id: 8,
    question: "What is a communication plan?",
    keywords: ["objective", "audience", "medium", "message"],
    scoreMode: "keyword",
  },
  {
    id: 9,
    question: "How would you document the impact of a livelihoods project?",
    keywords: ["photos", "video testimonials", "case studies"],
    scoreMode: "keyword",
  },
  {
    id: 10,
    question: "What are the elements of a good press release?",
    keywords: ["headline", "who/what/why", "quote", "contact"],
    scoreMode: "keyword",
  },
  {
    id: 11,
    question: "How can you use WhatsApp for community-level communication?",
    keywords: ["group info", "updates", "voice notes", "access"],
    scoreMode: "keyword",
  },
  {
    id: 12,
    question: "How do you handle negative news or feedback in the media?",
    keywords: ["transparency", "clarification", "official statement"],
    scoreMode: "keyword",
  },
  {
    id: 13,
    question: "What are the core values of TSF and how should they reflect in communication?",
    keywords: ["integrity", "dignity", "equity", "empathy"],
    scoreMode: "keyword",
  },
  {
    id: 14,
    question: "How do you plan content for different stakeholders (donors vs community)?",
    keywords: ["tailored messaging", "language", "impact vs emotion"],
    scoreMode: "keyword",
  },
  {
    id: 15,
    question: "What is internal communication and why is it important?",
    keywords: ["staff updates", "alignment", "morale"],
    scoreMode: "keyword",
  },
  {
    id: 16,
    question: "How do you measure the success of a communication campaign?",
    keywords: ["reach", "engagement", "feedback"],
    scoreMode: "keyword",
  },
  {
    id: 17,
    question: "What tools do you use for creating visual content?",
    keywords: ["Canva", "Photoshop", "Illustrator"],
    scoreMode: "keyword",
  },
  {
    id: 18,
    question: "What do you know about communication ethics?",
    keywords: ["accuracy", "sensitivity", "consent"],
    scoreMode: "keyword",
  },
  {
    id: 19,
    question: "How would you promote an upcoming community health camp?",
    keywords: ["posters", "word of mouth", "local radio"],
    scoreMode: "keyword",
  },
  {
    id: 20,
    question: "What makes a good photo for development storytelling?",
    keywords: ["emotion", "clarity", "context", "consent"],
    scoreMode: "keyword",
  },
  {
    id: 21,
    question: "What are some low-cost communication channels for remote areas?",
    keywords: ["posters", "wall painting", "mic announcements"],
    scoreMode: "keyword",
  },
  {
    id: 22,
    question: "How would you design a campaign to reduce school dropouts?",
    keywords: ["child rights", "parent meetings", "local influencers"],
    scoreMode: "keyword",
  },
  {
    id: 23,
    question: "How is branding important even for a non-profit like TSF?",
    keywords: ["trust", "recognition", "professional image"],
    scoreMode: "keyword",
  },
  {
    id: 24,
    question: "What’s the role of feedback in communication?",
    keywords: ["two-way", "improvement", "trust-building"],
    scoreMode: "keyword",
  },
  {
    id: 25,
    question: "How can you ensure your campaign respects tribal cultural values?",
    keywords: ["community consultation", "language", "customs"],
    scoreMode: "keyword",
  },
  {
    id: 26,
    question: "What is crisis communication?",
    keywords: ["emergency response", "reputation", "control narrative"],
    scoreMode: "keyword",
  },
  {
    id: 27,
    question: "How can short videos be used in community sensitization?",
    keywords: ["relatable", "mobile-friendly", "local language"],
    scoreMode: "keyword",
  },
  {
    id: 28,
    question: "How do you ensure content is accessible for people with low literacy?",
    keywords: ["audio", "visuals", "storytelling"],
    scoreMode: "keyword",
  },
  {
    id: 29,
    question: "What kind of content works well on LinkedIn for a foundation?",
    keywords: ["impact stories", "thought leadership", "events"],
    scoreMode: "keyword",
  },
  {
    id: 30,
    question: "How do you write an effective social media caption?",
    keywords: ["short", "engaging", "call-to-action"],
    scoreMode: "keyword",
  },
  {
    id: 31,
    question: "What do you understand by ‘voice of the community’?",
    keywords: ["inclusive representation", "local perspective"],
    scoreMode: "keyword",
  },
  {
    id: 32,
    question: "How do you maintain content consistency across platforms?",
    keywords: ["tone of voice", "visual identity", "approval flow"],
    scoreMode: "keyword",
  },
  {
    id: 33,
    question: "How can you make a boring but important topic engaging for the public?",
    keywords: ["infographics", "humor", "storytelling"],
    scoreMode: "keyword",
  },
  {
    id: 34,
    question: "What role does design play in communication for development?",
    keywords: ["clarity", "appeal", "comprehension"],
    scoreMode: "keyword",
  },
  {
    id: 35,
    question: "What are some common challenges in field communication?",
    keywords: ["network issues", "language", "fear", "misinformation"],
    scoreMode: "keyword",
  },
  {
    id: 36,
    question: "How do you plan a photo/video shoot in a village setting?",
    keywords: ["permissions", "consent", "weather", "context"],
    scoreMode: "keyword",
  },
  {
    id: 37,
    question: "What is a communication calendar?",
    keywords: ["monthly plan", "events", "deadlines"],
    scoreMode: "keyword",
  },
  {
    id: 38,
    question: "What are ‘key messages’ and why are they important?",
    keywords: ["focus points", "recall", "consistency"],
    scoreMode: "keyword",
  },
  {
    id: 39,
    question: "How do you communicate program success to funders?",
    keywords: ["reports", "infographics", "success metrics"],
    scoreMode: "keyword",
  },
  {
    id: 40,
    question: "Give an example of a communication initiative by TSF that you admire.",
    keywords: ["specific campaign", "impact", "message clarity"],
    scoreMode: "keyword",
  },
];
