const cseQuestions = [
  {
    id: 1,
    question: "What is civil society, and how is it important in development?",
    keywords: ["NGOs", "CBOs", "community participation", "empowerment"],
    scoreMode: "keyword",
  },
  {
    id: 2,
    question: "How can civil society contribute to inclusive governance?",
    keywords: ["accountability", "voice of people", "participatory planning"],
    scoreMode: "keyword",
  },
  {
    id: 3,
    question: "What role do NGOs play in rural development?",
    keywords: ["implementation", "awareness", "last-mile delivery"],
    scoreMode: "keyword",
  },
  {
    id: 4,
    question: "How would you identify active CBOs in a village?",
    keywords: ["PRA", "mapping", "local leaders", "gram sabha"],
    scoreMode: "keyword",
  },
  {
    id: 5,
    question: "How can TSF collaborate with local civil society groups?",
    keywords: ["MoUs", "joint programs", "community mobilization"],
    scoreMode: "keyword",
  },
  {
    id: 6,
    question: "What are the challenges in working with civil society organizations?",
    keywords: ["trust", "coordination", "capacity gaps"],
    scoreMode: "keyword",
  },
  {
    id: 7,
    question: "How do SHGs contribute to civil society empowerment?",
    keywords: ["collective action", "women empowerment", "savings"],
    scoreMode: "keyword",
  },
  {
    id: 8,
    question: "How would you ensure civil society is involved in a health or education project?",
    keywords: ["consultative meetings", "representation", "awareness"],
    scoreMode: "keyword",
  },
  {
    id: 9,
    question: "Why is transparency important in civil society engagement?",
    keywords: ["trust", "accountability", "participatory governance"],
    scoreMode: "keyword",
  },
  {
    id: 10,
    question: "How do you assess the credibility of a local NGO?",
    keywords: ["registration", "past work", "feedback from community"],
    scoreMode: "keyword",
  },
  {
    id: 11,
    question: "What do you know about Gram Sabhas and their role?",
    keywords: ["decision-making", "village planning", "accountability"],
    scoreMode: "keyword",
  },
  {
    id: 12,
    question: "How can civil society promote sustainable development goals (SDGs)?",
    keywords: ["advocacy", "awareness", "grassroots initiatives"],
    scoreMode: "keyword",
  },
  {
    id: 13,
    question: "What are some examples of successful civil society movements in India?",
    keywords: ["RTI", "NREGA", "Chipko", "Self-help movement"],
    scoreMode: "keyword",
  },
  {
    id: 14,
    question: "What is social audit, and how does civil society participate?",
    keywords: ["accountability", "transparency", "public hearing"],
    scoreMode: "keyword",
  },
  {
    id: 15,
    question: "What are common issues faced by civil society in tribal areas?",
    keywords: ["remoteness", "illiteracy", "language", "trust building"],
    scoreMode: "keyword",
  },
  {
    id: 16,
    question: "How would you build rapport with a new CBO in the village?",
    keywords: ["personal visits", "listening", "inclusive approach"],
    scoreMode: "keyword",
  },
  {
    id: 17,
    question: "How can youth-led organizations support social development?",
    keywords: ["innovation", "awareness drives", "local leadership"],
    scoreMode: "keyword",
  },
  {
    id: 18,
    question: "What is community-based monitoring?",
    keywords: ["citizen feedback", "service delivery", "local audit"],
    scoreMode: "keyword",
  },
  {
    id: 19,
    question: "How would you handle conflicts between CBOs in the same area?",
    keywords: ["neutral facilitation", "dialogue", "shared goals"],
    scoreMode: "keyword",
  },
  {
    id: 20,
    question: "What capacity-building activities can you conduct for CBOs?",
    keywords: ["leadership", "project mgmt", "documentation training"],
    scoreMode: "keyword",
  },
  {
    id: 21,
    question: "How does civil society strengthen democracy at the grassroots?",
    keywords: ["participation", "voice", "local accountability"],
    scoreMode: "keyword",
  },
  {
    id: 22,
    question: "What is your approach to mobilizing community participation?",
    keywords: ["awareness drives", "inclusive meetings", "IEC"],
    scoreMode: "keyword",
  },
  {
    id: 23,
    question: "How can civil society ensure gender inclusion in development?",
    keywords: ["representation", "women-led SHGs", "sensitization"],
    scoreMode: "keyword",
  },
  {
    id: 24,
    question: "What is the importance of multi-stakeholder engagement?",
    keywords: ["convergence", "shared resources", "collective impact"],
    scoreMode: "keyword",
  },
  {
    id: 25,
    question: "How do partnerships between CSOs and corporates work in CSR?",
    keywords: ["joint projects", "funding", "implementation partners"],
    scoreMode: "keyword",
  },
  {
    id: 26,
    question: "What are community-based organizations (CBOs)?",
    keywords: ["local", "informal/formal groups", "issue-focused"],
    scoreMode: "keyword",
  },
  {
    id: 27,
    question: "Why is civil society engagement important in the TSF model?",
    keywords: ["local ownership", "trust", "deeper reach"],
    scoreMode: "keyword",
  },
  {
    id: 28,
    question: "How do you handle political interference in community engagement?",
    keywords: ["neutrality", "transparency", "trust building"],
    scoreMode: "keyword",
  },
  {
    id: 29,
    question: "What indicators would you track in a civil society partnership?",
    keywords: ["participation", "outcome", "community satisfaction"],
    scoreMode: "keyword",
  },
  {
    id: 30,
    question: "How would you conduct a village-level stakeholder mapping?",
    keywords: ["listing", "categorization", "influence analysis"],
    scoreMode: "keyword",
  },
  {
    id: 31,
    question: "What is the importance of local leadership in civil society?",
    keywords: ["sustainability", "representation", "continuity"],
    scoreMode: "keyword",
  },
  {
    id: 32,
    question: "How do you promote inter-CBO collaboration?",
    keywords: ["joint activities", "cluster meetings", "resource pooling"],
    scoreMode: "keyword",
  },
  {
    id: 33,
    question: "What are Village Development Committees (VDCs)?",
    keywords: ["planning", "monitoring", "gram sabha link"],
    scoreMode: "keyword",
  },
  {
    id: 34,
    question: "How can technology support civil society engagement?",
    keywords: ["MIS", "WhatsApp groups", "mobile monitoring"],
    scoreMode: "keyword",
  },
  {
    id: 35,
    question: "How does civil society contribute during disaster response?",
    keywords: ["relief", "awareness", "last-mile support"],
    scoreMode: "keyword",
  },
  {
    id: 36,
    question: "How do you document the impact of civil society involvement?",
    keywords: ["case studies", "before-after", "community feedback"],
    scoreMode: "keyword",
  },
  {
    id: 37,
    question: "What is community mobilization, and why is it critical?",
    keywords: ["collective action", "ownership", "engagement"],
    scoreMode: "keyword",
  },
  {
    id: 38,
    question: "What kind of civil society initiatives does TSF support?",
    keywords: ["health", "education", "livelihoods", "inclusion"],
    scoreMode: "keyword",
  },
  {
    id: 39,
    question: "How would you train volunteers from civil society groups?",
    keywords: ["orientation", "role clarity", "exposure visits"],
    scoreMode: "keyword",
  },
  {
    id: 40,
    question: "What’s the difference between top-down vs bottom-up development approaches?",
    keywords: ["participatory", "local solutions", "empowerment"],
    scoreMode: "keyword",
  },
];
