const disabilityInclusionQuestions = [
  {
    id: 1,
    question: "What do you understand by disability inclusion?",
    keywords: ["equal opportunity", "accessibility", "participation"],
    scoreMode: "keyword",
  },
  {
    id: 2,
    question: "What are the different types of disabilities?",
    keywords: ["physical", "sensory", "intellectual", "multiple"],
    scoreMode: "keyword",
  },
  {
    id: 3,
    question: "How would you identify Persons with Disabilities (PwDs) in a village?",
    keywords: ["community mapping", "door-to-door", "disability certificates"],
    scoreMode: "keyword",
  },
  {
    id: 4,
    question: "What is the role of assistive devices in inclusion?",
    keywords: ["mobility", "independence", "dignity"],
    scoreMode: "keyword",
  },
  {
    id: 5,
    question: "What are the challenges PwDs face in rural India?",
    keywords: ["stigma", "inaccessibility", "lack of services"],
    scoreMode: "keyword",
  },
  {
    id: 6,
    question: "How can SHGs empower people with disabilities?",
    keywords: ["livelihood", "confidence", "community bonding"],
    scoreMode: "keyword",
  },
  {
    id: 7,
    question: "What are disability certificates and who issues them?",
    keywords: ["medical board", "UDID", "proof of disability"],
    scoreMode: "keyword",
  },
  {
    id: 8,
    question: "What is your understanding of the RPwD Act, 2016?",
    keywords: ["rights", "reservations", "anti-discrimination"],
    scoreMode: "keyword",
  },
  {
    id: 9,
    question: "How would you make a community event inclusive for PwDs?",
    keywords: ["ramps", "sign language", "priority seating"],
    scoreMode: "keyword",
  },
  {
    id: 10,
    question: "Why is community sensitization important?",
    keywords: ["attitude change", "awareness", "empathy"],
    scoreMode: "keyword",
  },
  {
    id: 11,
    question: "How does TSF support people with disabilities?",
    keywords: ["access", "livelihood", "health support", "inclusion"],
    scoreMode: "keyword",
  },
  {
    id: 12,
    question: "What is inclusive education and why is it important?",
    keywords: ["mainstream schooling", "reasonable accommodation"],
    scoreMode: "keyword",
  },
  {
    id: 13,
    question: "How can vocational training benefit PwDs?",
    keywords: ["employability", "skill-building", "income"],
    scoreMode: "keyword",
  },
  {
    id: 14,
    question: "What are some government schemes for PwDs?",
    keywords: ["ADIP", "NIRAMAYA", "scholarships", "pensions"],
    scoreMode: "keyword",
  },
  {
    id: 15,
    question: "How would you promote livelihoods for PwDs in rural areas?",
    keywords: ["skill-based training", "SHGs", "market linkages"],
    scoreMode: "keyword",
  },
  {
    id: 16,
    question: "What is barrier-free infrastructure?",
    keywords: ["ramps", "handrails", "signage", "accessible toilets"],
    scoreMode: "keyword",
  },
  {
    id: 17,
    question: "How would you help a disabled child get enrolled in school?",
    keywords: ["support services", "advocacy", "coordination"],
    scoreMode: "keyword",
  },
  {
    id: 18,
    question: "What is the role of caregivers in disability care?",
    keywords: ["daily support", "emotional care", "advocacy"],
    scoreMode: "keyword",
  },
  {
    id: 19,
    question: "Why is mental health support important for PwDs?",
    keywords: ["emotional well-being", "social inclusion", "support systems"],
    scoreMode: "keyword",
  },
  {
    id: 20,
    question: "How do you promote dignity and independence for PwDs?",
    keywords: ["rights-based approach", "respect", "empowerment"],
    scoreMode: "keyword",
  },
  {
    id: 21,
    question: "What do you understand by inclusive sports?",
    keywords: ["participation", "adapted equipment", "equality"],
    scoreMode: "keyword",
  },
  {
    id: 22,
    question: "What is the role of physiotherapy in rehabilitation?",
    keywords: ["mobility improvement", "recovery", "functionality"],
    scoreMode: "keyword",
  },
  {
    id: 23,
    question: "How can a disabled person access govt schemes?",
    keywords: ["disability ID", "awareness", "facilitation"],
    scoreMode: "keyword",
  },
  {
    id: 24,
    question: "How would you support a PwD facing domestic violence?",
    keywords: ["legal aid", "helpline", "shelter", "counseling"],
    scoreMode: "keyword",
  },
  {
    id: 25,
    question: "What is community-based rehabilitation (CBR)?",
    keywords: ["localized care", "family involvement", "participation"],
    scoreMode: "keyword",
  },
  {
    id: 26,
    question: "How do you measure disability inclusion in a project?",
    keywords: ["indicators", "participation rates", "feedback"],
    scoreMode: "keyword",
  },
  {
    id: 27,
    question: "What is accessibility audit?",
    keywords: ["evaluation", "infrastructure", "recommendations"],
    scoreMode: "keyword",
  },
  {
    id: 28,
    question: "How do you involve PwDs in decision-making?",
    keywords: ["leadership roles", "consultation", "representation"],
    scoreMode: "keyword",
  },
  {
    id: 29,
    question: "What are inclusive livelihood models?",
    keywords: ["home-based", "flexible hours", "skill-matched"],
    scoreMode: "keyword",
  },
  {
    id: 30,
    question: "Why is social security important for PwDs?",
    keywords: ["income protection", "healthcare", "dignity"],
    scoreMode: "keyword",
  },
  {
    id: 31,
    question: "What do you know about inclusive hiring practices?",
    keywords: ["reservation", "job roles", "sensitization"],
    scoreMode: "keyword",
  },
  {
    id: 32,
    question: "What is the significance of the International Day of Persons with Disabilities?",
    keywords: ["awareness", "celebration", "visibility"],
    scoreMode: "keyword",
  },
  {
    id: 33,
    question: "How do you address attitudinal barriers?",
    keywords: ["campaigns", "storytelling", "role models"],
    scoreMode: "keyword",
  },
  {
    id: 34,
    question: "What is the function of a District Disability Rehabilitation Centre (DDRC)?",
    keywords: ["therapy", "device distribution", "counseling"],
    scoreMode: "keyword",
  },
  {
    id: 35,
    question: "How would you design an awareness session for school children on disability?",
    keywords: ["interactive", "empathy", "inclusive games"],
    scoreMode: "keyword",
  },
  {
    id: 36,
    question: "Why is early intervention critical for children with disabilities?",
    keywords: ["development", "support", "prognosis"],
    scoreMode: "keyword",
  },
  {
    id: 37,
    question: "How can parents of disabled children be supported?",
    keywords: ["counseling", "peer networks", "training"],
    scoreMode: "keyword",
  },
  {
    id: 38,
    question: "How do you plan a disability survey in a block or panchayat?",
    keywords: ["structured forms", "local facilitators", "privacy"],
    scoreMode: "keyword",
  },
  {
    id: 39,
    question: "What is universal design and how is it relevant?",
    keywords: ["usable by all", "inclusive architecture"],
    scoreMode: "keyword",
  },
  {
    id: 40,
    question: "Name a TSF initiative related to disability and what makes it impactful.",
    keywords: ["Rishta", "accessibility drives", "skill programs"],
    scoreMode: "keyword",
  },
];

