export const sports = [
  {
    id: 1,
    question: "How do you see the role of sports in community development?",
    keywords: ["unity", "discipline", "teamwork", "empowerment"],
    scoreMode: "keyword",
  },
  {
    id: 2,
    question: "What are the core objectives of TSF’s sports initiatives?",
    keywords: ["inclusivity", "talent identification", "rural youth"],
    scoreMode: "keyword",
  },
  {
    id: 3,
    question: "How does sports contribute to youth empowerment?",
    keywords: ["leadership", "confidence", "health", "focus"],
    scoreMode: "keyword",
  },
  {
    id: 4,
    question: "What are the challenges faced by rural athletes in India?",
    keywords: ["access", "funding", "coaching", "awareness"],
    scoreMode: "keyword",
  },
  {
    id: 5,
    question: "How can sports be used as a tool for social inclusion?",
    keywords: ["gender equality", "tribal inclusion", "marginalised"],
    scoreMode: "keyword",
  },
  {
    id: 6,
    question: "What kind of infrastructure is needed for sports development?",
    keywords: ["playgrounds", "equipment", "coaches"],
    scoreMode: "keyword",
  },
  {
    id: 7,
    question: "Name any TSF-supported sports initiatives you are aware of.",
    keywords: ["Naval Tata Hockey Academy", "Football Training", "Athletics Camps"],
    scoreMode: "keyword",
  },
  {
    id: 8,
    question: "How would you identify sports talent in rural areas?",
    keywords: ["camps", "school visits", "community referrals"],
    scoreMode: "keyword",
  },
  {
    id: 9,
    question: "Why is it important to train local coaches?",
    keywords: ["sustainability", "community leadership", "trust"],
    scoreMode: "keyword",
  },
  {
    id: 10,
    question: "How can schools promote sports among children?",
    keywords: ["PE curriculum", "inter-school events", "incentives"],
    scoreMode: "keyword",
  },
  {
    id: 11,
    question: "What is the role of parents in encouraging sports?",
    keywords: ["support", "motivation", "prioritization"],
    scoreMode: "keyword",
  },
  {
    id: 12,
    question: "How do you ensure girls actively participate in sports?",
    keywords: ["safe spaces", "sensitization", "equal opportunities"],
    scoreMode: "keyword",
  },
  {
    id: 13,
    question: "How can sports improve mental health in youth?",
    keywords: ["stress relief", "focus", "confidence"],
    scoreMode: "keyword",
  },
  {
    id: 14,
    question: "What’s your opinion on sports scholarships?",
    keywords: ["access", "motivation", "opportunities"],
    scoreMode: "keyword",
  },
  {
    id: 15,
    question: "How would you promote indigenous games in villages?",
    keywords: ["local tournaments", "elders’ participation", "cultural pride"],
    scoreMode: "keyword",
  },
  {
    id: 16,
    question: "How is sports linked to holistic education?",
    keywords: ["personality", "discipline", "learning by doing"],
    scoreMode: "keyword",
  },
  {
    id: 17,
    question: "How would you structure a weekly sports training session?",
    keywords: ["warm-up", "drills", "game", "cool-down"],
    scoreMode: "keyword",
  },
  {
    id: 18,
    question: "What is a community sports event and why is it important?",
    keywords: ["engagement", "visibility", "awareness"],
    scoreMode: "keyword",
  },
  {
    id: 19,
    question: "Why is early sports exposure critical in a child’s life?",
    keywords: ["physical development", "habit formation"],
    scoreMode: "keyword",
  },
  {
    id: 20,
    question: "What strategies would you use to boost girls’ sports enrollment?",
    keywords: ["role models", "parents’ meets", "safety assurances"],
    scoreMode: "keyword",
  },
  {
    id: 21,
    question: "What’s your view on nutrition in athletes’ development?",
    keywords: ["stamina", "performance", "recovery"],
    scoreMode: "keyword",
  },
  {
    id: 22,
    question: "How can TSF help tribal communities through sports?",
    keywords: ["identity", "representation", "confidence"],
    scoreMode: "keyword",
  },
  {
    id: 23,
    question: "How would you handle competition-related pressure in youth?",
    keywords: ["counseling", "motivation", "sportsmanship"],
    scoreMode: "keyword",
  },
  {
    id: 24,
    question: "What values do sports instill in young individuals?",
    keywords: ["discipline", "resilience", "fairness", "goal-setting"],
    scoreMode: "keyword",
  },
  {
    id: 25,
    question: "How can sports be linked with livelihood opportunities?",
    keywords: ["coaching", "refereeing", "scholarships"],
    scoreMode: "keyword",
  },
  {
    id: 26,
    question: "What challenges are faced in sustaining rural sports programs?",
    keywords: ["funding", "dropout", "migration"],
    scoreMode: "keyword",
  },
  {
    id: 27,
    question: "How does TSF identify and support promising athletes?",
    keywords: ["trials", "continuous training", "mentorship"],
    scoreMode: "keyword",
  },
  {
    id: 28,
    question: "What is a sports ecosystem and why is it important?",
    keywords: ["coaching", "support systems", "infrastructure"],
    scoreMode: "keyword",
  },
  {
    id: 29,
    question: "How can community volunteers support sports development?",
    keywords: ["organizing events", "mobilizing children", "mentoring"],
    scoreMode: "keyword",
  },
  {
    id: 30,
    question: "Why is regular monitoring important in sports training?",
    keywords: ["progress tracking", "discipline", "feedback"],
    scoreMode: "keyword",
  },
  {
    id: 31,
    question: "What role does fitness play in sports performance?",
    keywords: ["strength", "agility", "endurance"],
    scoreMode: "keyword",
  },
  {
    id: 32,
    question: "How would you prepare for a grassroots sports event?",
    keywords: ["logistics", "mobilization", "permissions"],
    scoreMode: "keyword",
  },
  {
    id: 33,
    question: "What are your ideas for engaging out-of-school youth in sports?",
    keywords: ["drop-in sessions", "local leagues", "mentors"],
    scoreMode: "keyword",
  },
  {
    id: 34,
    question: "How can digital platforms aid sports training today?",
    keywords: ["online coaching", "analytics", "video review"],
    scoreMode: "keyword",
  },
  {
    id: 35,
    question: "Why are sports role models important in rural areas?",
    keywords: ["aspiration", "motivation", "relatability"],
    scoreMode: "keyword",
  },
  {
    id: 36,
    question: "How do TSF’s sports programs align with the Sustainable Development Goals (SDGs)?",
    keywords: ["health", "gender equality", "education", "inclusion"],
    scoreMode: "keyword",
  },
  {
    id: 37,
    question: "What safety measures are necessary during sports sessions?",
    keywords: ["first-aid", "hydration", "supervision"],
    scoreMode: "keyword",
  },
  {
    id: 38,
    question: "How does teamwork in sports translate to life skills?",
    keywords: ["communication", "empathy", "responsibility"],
    scoreMode: "keyword",
  },
  {
    id: 39,
    question: "What would be your approach to developing sports in a tribal village?",
    keywords: ["community buy-in", "customized training", "cultural games"],
    scoreMode: "keyword",
  },
  {
    id: 40,
    question: "Suggest one innovative idea to promote sports among youth in rural Jharkhand.",
    keywords: ["mobile sports van", "youth clubs", "gamified learning"],
    scoreMode: "keyword",
  },
];